apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-docker
  template:
    metadata:
      labels:
        app: dotnet-docker
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: api
        image: registry.cloud.okteto.net/ranajitcse2009/dotnet-docker
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-docker
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: dotnet-docker
spec:
  type: ClusterIP
  ports:
    - name: dotnet-docker
      port: 5000
  selector:
    app: dotnet-docker
